// Self-improving eval loop -- grounded in Dynabench (Kiela et al., NAACL 2021,
// "Rethinking Benchmarking in NLP"): a benchmark stays informative only if its
// test set keeps expanding toward the subject's actual weak points, not a
// fixed snapshot. Dynabench does this with a human annotator adversarially
// probing a live model in the loop; we don't have a human-in-the-loop step
// here, so this is the model-only half of that pattern -- every CONFIRMED
// finding is fed back to a local judge model, which proposes ONE new,
// sharper adversarial variant that specifically tries to break past what the
// current task already caught. This mirrors the practical version of the
// same idea (Arize, "Techniques for Self-Improving LLM Evals"): every real
// failure becomes the seed for a future regression test, not just a one-off
// bug report.
//
// This is a proposal generator, not an auto-merge: every output goes to
// PROPOSED_TASKS.md for a human to read, accept, reject, or rewrite before it
// becomes tasks/task-NN. That review gate is deliberate -- an unreviewed
// model-proposed task is exactly the kind of thing that quietly rots a
// benchmark's credibility if it ships without a human reading it first.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const findings = JSON.parse(readFileSync(path.join(__dirname, "..", "findings.json"), "utf-8"));

async function proposeVariant(finding) {
  const prompt = `You are helping extend an adversarial reliability benchmark for a background-job platform (Trigger.dev).

Here is a CONFIRMED finding from an existing benchmark task:
- Task: ${finding.task}
- Category: ${finding.category}
- Result: ${finding.result}
- Finding: ${finding.finding}

Propose exactly ONE new, more adversarial test scenario that builds on this finding and tries to find a DEEPER or ADJACENT failure the current task does not already cover. Be concrete and specific to background-job/durable-execution platforms (queues, retries, idempotency, crash recovery, concurrency, deploy versioning). Do not restate the existing finding.

Respond with strict JSON only, no markdown, no prose outside the JSON:
{"proposed_scenario": "...", "adversarial_angle": "...", "why_deeper": "..."}`;

  const res = await fetch("http://localhost:11434/api/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ model: "nemotron-mini", prompt, stream: false, format: "json" }),
  });
  if (!res.ok) throw new Error(`Ollama call failed: ${res.status}`);
  const data = await res.json();
  try {
    return JSON.parse(data.response);
  } catch {
    return { proposed_scenario: null, adversarial_angle: null, why_deeper: null, raw: data.response };
  }
}

const proposals = [];
for (const finding of findings) {
  console.log(`Proposing a follow-up for ${finding.task}...`);
  const proposal = await proposeVariant(finding);
  proposals.push({ source_task: finding.task, source_result: finding.result, ...proposal });
}

writeFileSync(path.join(__dirname, "..", "candidates.json"), JSON.stringify(proposals, null, 2));

const md = [
  "# Proposed follow-up tasks (unreviewed)",
  "",
  "Generated by `scoring/self_improve.mjs` -- a local judge model (nemotron-mini)",
  "proposed one adversarial follow-up per existing finding, per Dynabench's",
  "model-in-the-loop pattern. **Nothing here is a task yet.** Each entry needs a",
  "human to read it, decide if it's worth building, and if so write it as a real",
  "`tasks/task-NN` following the format in `shared/README.md` -- the same way",
  "every existing task in this repo was hand-built and live-verified, not",
  "auto-generated wholesale.",
  "",
  ...proposals.map(
    (p, i) =>
      `## Candidate ${i + 1} — follow-up to \`${p.source_task}\` (${p.source_result})\n\n` +
      `**Proposed scenario:** ${p.proposed_scenario ?? "(model did not return valid JSON)"}\n\n` +
      (p.adversarial_angle ? `**Adversarial angle:** ${p.adversarial_angle}\n\n` : "") +
      (p.why_deeper ? `**Why this goes deeper:** ${p.why_deeper}\n` : "")
  ),
].join("\n");

writeFileSync(path.join(__dirname, "..", "PROPOSED_TASKS.md"), md);
console.log(`\nWrote ${proposals.length} proposals to PROPOSED_TASKS.md and candidates.json`);
